//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Spatial {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Spatial.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array arguments must have the same length..
        /// </summary>
        internal static string ArgumentArraysSameLength {
            get {
                return ResourceManager.GetString("ArgumentArraysSameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given array is the wrong length. Should be {0}..
        /// </summary>
        internal static string ArgumentArrayWrongLength {
            get {
                return ResourceManager.GetString("ArgumentArrayWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must be between 0 and 1..
        /// </summary>
        internal static string ArgumentBetweenZeroAndOne {
            get {
                return ResourceManager.GetString("ArgumentBetweenZeroAndOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be in the range -1 &lt; x &lt; 1..
        /// </summary>
        internal static string ArgumentCannotBeBetweenOneAndNegativeOne {
            get {
                return ResourceManager.GetString("ArgumentCannotBeBetweenOneAndNegativeOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be even..
        /// </summary>
        internal static string ArgumentEven {
            get {
                return ResourceManager.GetString("ArgumentEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one item of {0} is a null reference (Nothing in Visual Basic)..
        /// </summary>
        internal static string ArgumentItemNull {
            get {
                return ResourceManager.GetString("ArgumentItemNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than or equal to one..
        /// </summary>
        internal static string ArgumentLessThanOne {
            get {
                return ResourceManager.GetString("ArgumentLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix dimension mismatch..
        /// </summary>
        internal static string ArgumentMatrixDimensions {
            get {
                return ResourceManager.GetString("ArgumentMatrixDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix dimension mismatch: {0}..
        /// </summary>
        internal static string ArgumentMatrixDimensions1 {
            get {
                return ResourceManager.GetString("ArgumentMatrixDimensions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix dimension mismatch: first operand is {0}, second operand is {1}..
        /// </summary>
        internal static string ArgumentMatrixDimensions2 {
            get {
                return ResourceManager.GetString("ArgumentMatrixDimensions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix dimension mismatch: first operand is {0}, second operand is {1}, third operand is {2}..
        /// </summary>
        internal static string ArgumentMatrixDimensions3 {
            get {
                return ResourceManager.GetString("ArgumentMatrixDimensions3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested matrix does not exist..
        /// </summary>
        internal static string ArgumentMatrixDoesNotExist {
            get {
                return ResourceManager.GetString("ArgumentMatrixDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matrix indices must not be out of range of the given matrix..
        /// </summary>
        internal static string ArgumentMatrixIndexOutOfRange {
            get {
                return ResourceManager.GetString("ArgumentMatrixIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must be positive definite..
        /// </summary>
        internal static string ArgumentMatrixPositiveDefinite {
            get {
                return ResourceManager.GetString("ArgumentMatrixPositiveDefinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix column dimension mismatch..
        /// </summary>
        internal static string ArgumentMatrixSameColumnDimension {
            get {
                return ResourceManager.GetString("ArgumentMatrixSameColumnDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix row dimension mismatch..
        /// </summary>
        internal static string ArgumentMatrixSameRowDimension {
            get {
                return ResourceManager.GetString("ArgumentMatrixSameRowDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must have exactly one column..
        /// </summary>
        internal static string ArgumentMatrixSingleColumn {
            get {
                return ResourceManager.GetString("ArgumentMatrixSingleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must have exactly one column and row, thus have only one cell..
        /// </summary>
        internal static string ArgumentMatrixSingleColumnRow {
            get {
                return ResourceManager.GetString("ArgumentMatrixSingleColumnRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must have exactly one row..
        /// </summary>
        internal static string ArgumentMatrixSingleRow {
            get {
                return ResourceManager.GetString("ArgumentMatrixSingleRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must be square..
        /// </summary>
        internal static string ArgumentMatrixSquare {
            get {
                return ResourceManager.GetString("ArgumentMatrixSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must be symmetric..
        /// </summary>
        internal static string ArgumentMatrixSymmetric {
            get {
                return ResourceManager.GetString("ArgumentMatrixSymmetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must be symmetric positive definite..
        /// </summary>
        internal static string ArgumentMatrixSymmetricPositiveDefinite {
            get {
                return ResourceManager.GetString("ArgumentMatrixSymmetricPositiveDefinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the specified range, the minimum is greater than maximum..
        /// </summary>
        internal static string ArgumentMinValueGreaterThanMaxValue {
            get {
                return ResourceManager.GetString("ArgumentMinValueGreaterThanMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be positive..
        /// </summary>
        internal static string ArgumentMustBePositive {
            get {
                return ResourceManager.GetString("ArgumentMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must neither be infinite nor NaN..
        /// </summary>
        internal static string ArgumentNotInfinityNaN {
            get {
                return ResourceManager.GetString("ArgumentNotInfinityNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must not be negative (zero is ok)..
        /// </summary>
        internal static string ArgumentNotNegative {
            get {
                return ResourceManager.GetString("ArgumentNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a null reference (Nothing in Visual Basic)..
        /// </summary>
        internal static string ArgumentNull {
            get {
                return ResourceManager.GetString("ArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be odd..
        /// </summary>
        internal static string ArgumentOdd {
            get {
                return ResourceManager.GetString("ArgumentOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen parameter set is invalid (probably some value is out of range)..
        /// </summary>
        internal static string ArgumentParameterSetInvalid {
            get {
                return ResourceManager.GetString("ArgumentParameterSetInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be positive (and not zero)..
        /// </summary>
        internal static string ArgumentPositive {
            get {
                return ResourceManager.GetString("ArgumentPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size must be a Power of Two..
        /// </summary>
        internal static string ArgumentPowerOfTwo {
            get {
                return ResourceManager.GetString("ArgumentPowerOfTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size must be a Power of Two in every dimension..
        /// </summary>
        internal static string ArgumentPowerOfTwoEveryDimension {
            get {
                return ResourceManager.GetString("ArgumentPowerOfTwoEveryDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments must be different objects..
        /// </summary>
        internal static string ArgumentReferenceDifferent {
            get {
                return ResourceManager.GetString("ArgumentReferenceDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array must have exactly one dimension (and not be null)..
        /// </summary>
        internal static string ArgumentSingleDimensionArray {
            get {
                return ResourceManager.GetString("ArgumentSingleDimensionArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type mismatch..
        /// </summary>
        internal static string ArgumentTypeMismatch {
            get {
                return ResourceManager.GetString("ArgumentTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upper bound must be strictly larger than the lower bound..
        /// </summary>
        internal static string ArgumentUpperBoundMustBeLargerThanLowerBound {
            get {
                return ResourceManager.GetString("ArgumentUpperBoundMustBeLargerThanLowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upper bound must be at least as large as the lower bound..
        /// </summary>
        internal static string ArgumentUpperBoundMustBeLargerThanOrEqualToLowerBound {
            get {
                return ResourceManager.GetString("ArgumentUpperBoundMustBeLargerThanOrEqualToLowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dimension of {0} mismatches the expected value or is invalid for the operation..
        /// </summary>
        internal static string ArgumentVectorDimensionMismatch {
            get {
                return ResourceManager.GetString("ArgumentVectorDimensionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dimension of {0} mismatches the expected value or is invalid for the operation, expected dimension {1}..
        /// </summary>
        internal static string ArgumentVectorDimensionMismatchExpecting {
            get {
                return ResourceManager.GetString("ArgumentVectorDimensionMismatchExpecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array length must be a multiple of {0}..
        /// </summary>
        internal static string ArgumentVectorLengthsMultipleOf {
            get {
                return ResourceManager.GetString("ArgumentVectorLengthsMultipleOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All vectors must have the same dimensionality..
        /// </summary>
        internal static string ArgumentVectorsSameLength {
            get {
                return ResourceManager.GetString("ArgumentVectorsSameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vector must have 3 dimensions..
        /// </summary>
        internal static string ArgumentVectorThreeDimensional {
            get {
                return ResourceManager.GetString("ArgumentVectorThreeDimensional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given array is too small. It must be at least {0} long..
        /// </summary>
        internal static string ArrayTooSmall {
            get {
                return ResourceManager.GetString("ArrayTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given file doesn&apos;t exist..
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of columns of a matrix must be positive..
        /// </summary>
        internal static string MatrixColumnsMustBePositive {
            get {
                return ResourceManager.GetString("MatrixColumnsMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of rows of a matrix must be positive..
        /// </summary>
        internal static string MatrixRowsMustBePositive {
            get {
                return ResourceManager.GetString("MatrixRowsMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of rows or columns of a matrix must be positive..
        /// </summary>
        internal static string MatrixRowsOrColumnsMustBePositive {
            get {
                return ResourceManager.GetString("MatrixRowsOrColumnsMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 1 and 2 dimensional arrays are supported..
        /// </summary>
        internal static string MoreThan2D {
            get {
                return ResourceManager.GetString("MoreThan2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data must contain at least {0} values..
        /// </summary>
        internal static string MustContainAtLeast {
            get {
                return ResourceManager.GetString("MustContainAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot contain a space. name:  {0}.
        /// </summary>
        internal static string NameCannotContainASpace {
            get {
                return ResourceManager.GetString("NameCannotContainASpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not implemented yet..
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a supported type..
        /// </summary>
        internal static string NotSupportedType {
            get {
                return ResourceManager.GetString("NotSupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The algorithm has failed, exceeded the number of iterations allowed or there is no root within the provided bounds..
        /// </summary>
        internal static string RootFindingFailed {
            get {
                return ResourceManager.GetString("RootFindingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lower and upper bounds must bracket a single root..
        /// </summary>
        internal static string RootMustBeBracketedByBounds {
            get {
                return ResourceManager.GetString("RootMustBeBracketedByBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The algorithm ended without root in the range..
        /// </summary>
        internal static string RootNotFound {
            get {
                return ResourceManager.GetString("RootNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of rows must greater than or equal to the number of columns..
        /// </summary>
        internal static string RowsLessThanColumns {
            get {
                return ResourceManager.GetString("RowsLessThanColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given stop criterion already exist in the collection..
        /// </summary>
        internal static string StopCriterionDuplicate {
            get {
                return ResourceManager.GetString("StopCriterionDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no stop criterion in the collection..
        /// </summary>
        internal static string StopCriterionMissing {
            get {
                return ResourceManager.GetString("StopCriterionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String parameter cannot be empty or null..
        /// </summary>
        internal static string StringNullOrEmpty {
            get {
                return ResourceManager.GetString("StringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We only support sparse matrix with less than int.MaxValue elements..
        /// </summary>
        internal static string TooManyElements {
            get {
                return ResourceManager.GetString("TooManyElements", resourceCulture);
            }
        }
    }
}
