//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is greater than {1}.
        /// </summary>
        internal static string ArgumentOutOfRangeGreater {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is greater or equal than {1}.
        /// </summary>
        internal static string ArgumentOutOfRangeGreaterOrEqual {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeGreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is less than {1}.
        /// </summary>
        internal static string ArgumentOutOfRangeLess {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is less or equal than {1}.
        /// </summary>
        internal static string ArgumentOutOfRangeLessOrEqual {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeLessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is too large..
        /// </summary>
        internal static string ArgumentOutOfRangeTooLarge {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is too small..
        /// </summary>
        internal static string ArgumentOutOfRangeTooSmall {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type mismatch..
        /// </summary>
        internal static string ArgumentTypeMismatch {
            get {
                return ResourceManager.GetString("ArgumentTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object is already disposed.
        /// </summary>
        internal static string ObjectAlreadyDisposed {
            get {
                return ResourceManager.GetString("ObjectAlreadyDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object pool is empty.
        /// </summary>
        internal static string OBJECT_POOL_EMPTY {
            get {
                return ResourceManager.GetString("OBJECT_POOL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object pool is full.
        /// </summary>
        internal static string OBJECT_POOL_FULL {
            get {
                return ResourceManager.GetString("OBJECT_POOL_FULL", resourceCulture);
            }
        }
    }
}
